### ISSUE TITLE
NTR: pterygoid process

### ISSUE THREAD

**Issue by sabrinatoro** [cerivs/zebrafish-anatomical-ontology#139]
Information from the introduction of ZDB-PUB-180124-2: 
- cartilaginous pterygoid process (Ptp) is a late-forming extension of the palatoquadrate cartilage
- the zebrafish Ptp is derived from cells located in the maxillary prominence of the first pharyngeal arch
(refers to Cubbage and Mabee, 1996)

As per Ceri's request:
adding the following link as one of the first uses of pterygoid process 
https://zfin.org/ZDB-FIG-090324-27

**Comment by cerivs** [comment]
A medial cartilaginous spur that develops from the dorsomedial edge of the palatoquadrate.  It is derived from cells located in the maxillary prominence of the first pharyngeal arch and gives rise to the metapterygoid. ZDB-PUB-961014-192 I made the structure start at High Pec because there are some images where it had formed and was visible by 48 hours. Ends at 14-20 days when t6he metapterygoid forms.
